---

- name: install nvidia driver and utils
  apt:
    update_cache: true
    state: present
    force_apt_get: true
    pkg:
      - nvidia-headless-570
      - nvidia-utils-570
  register: driver

- name: reboot the machine when drivers changed
  reboot:
  when: driver.changed
