---
- name: ensure ceph common is present
  apt:
    name: ceph-common
    state: present
    force_apt_get: true

- name: add cephfs secret
  copy:
    dest: /etc/ceph/client.ai.secret
    content: "{{ secret }}"

- name: add mount
  mount:
    path: /home
    src: 172.21.232.61:6789,172.21.232.14:6789,172.21.232.15:6789:/ai/{{ inventory_file | basename }}
    fstype: ceph
    opts: "name={{ user }},secretfile=/etc/ceph/client.ai.secret"
    state: present