---

- name: ensure munge is installed
  apt:
    name: munge
    update_cache: true
    state: present
    force_apt_get: true

- name: fetch munge private keys
  slurp:
    src: /etc/munge/munge.key
  register: mungekey
  changed_when: false

- set_fact:
    mungekey_content: "{{ mungekey['content'] }}"

- name: distribute controllers private key
  copy:
    dest: /etc/munge/munge.key
    content: "{{ hostvars['slurm-controller'].mungekey_content | b64decode }}"
  register: keydistribution

- name: ensure munge is restarted when key changed
  service:
    name: munge
    state: restarted
  when: keydistribution.changed

- name: ensure munge is enabled and running
  service:
    name: munge
    enabled: true
    state: started

