---
# Various factors have led to this hack.
# * We have no good way of sharing the general ansible applied to the cluster 
#   before handing them over to this project.
# * System administrators should use their real id when configuring the cloud, 
#   but the current Slurm installation by NVIDIA DEEPOPS seems to break pam and thereby said logins. 
#   (Users don't need to access the compute nodes anyways, so not a dealbreaker)
# * Updating to the latest Slurm (21.08 at the moment) makes DEEPOPS unable to build Slurm.
# * Dropping DEEPOPS extends this project scope quite a bit: 
#   We would lose a lot of Nvidia knowledge and have to set up everything ourselves.
# * Dropping the pre-applied ansible also extends the scope: 
#   Aicloud would have to deal with active directory logins and configuration.
#
# The easiest path forward is adding a service account and just letting ad logins break on compute nodes.
#
# FIXME: revisit this in the future ...
#
- name: serviceuser
  hosts: all
  tasks:
    - name: add serviceuser
      user:
        name: serviceuser
        home: /serviceuser # outside of /home
        skeleton: /etc/skel
        shell: /bin/bash

    - name: allow serviceuser to sudo without password
      copy:
        dest: /etc/sudoers.d/serviceuser
        content: serviceuser ALL=(ALL) NOPASSWD:ALL
        mode: 0440
    
    - name: add authorized_keys
      authorized_key:
        user: serviceuser
        state: present
        key: '{{ item }}'
      with_items:
        - https://github.com/fasmide.keys
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCjrqorlR39Vc+cxyrPu29EblMifDLBMum7nLzWXhzqcB4gXXVqU3Bnlzp+BVhWFzXe15XY+nBQErVx+sETkei8gouDueDxu0mgUM1QAOSnhQoGBSuJ4E8y39NuFDVO+ddGG8d+SqUJ5hllfEA6tjNT/WYgE18vVjjZD0W1QC8K/dcqdlKSLxDH9dqoBbvCyse2ZAJzOawEl7VLuvslopN6Z+aOOb8f/vMOd5QnqeL3w1yf0YN4d+R/vYikkgJJQSu/TsUjn9vPKmrJFzs9Tzxv9qyGDgFST9Irneyx7c95LjsDn0qvmrBBNgRQdkejmvmjaqW/2ryfxJkENmE/aSO9 tha@tha-colfax
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCodeKVWF6mMEU+yI63hk17fiyKn9DGqIk1Civ3121/mZBTW38cmsIL3bNIWZYXI86Q2wSUPce72N9dXi+xC2Od07D/g/DRKBQ86YUXTDWVJhSjZ2y968Z4lK/NufEVZa+LVaNpQvOI6QiJZtbnztrWw3wn9Iw338TrchoSPuWutD8JzK5mbWnvOFgxoKhrrs9MtFQ/T5tgGuultGdzdJ8DtU22jdsQkp0aREpKhRYQxZI6k59W0JX8jgPL364KLBoihc1wKKoRkvDcM2sJFW4PsWYF/uBB9oIGpBa287AswXBIiDgFeCUG85rPQveErMFZn1TvxC95x647xMGmXXqr tlj@tlj-ThinkPad-T470p
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCx/2rg/FUFa+j8//vNGJBRhEZz7dvuNj3966Vx9s6cmUZR+mG+5N2C6tCZv/PxLkW7SPSpzNnNYhkZuo93Uhmw8nWfYs8lRJgWvQ1XccjphJr7tPcr/o6wh47iqpmPvN4u0Q86VC9bj363bnFad/Yag8oY+zro6BQ7/5TtasEayQ6bICzDUEbeiK5lDKDMBgTSyw7teLR7E4DiqOG39EHLD8AxQKhkmeG77q+1Ojfurz7hy7qJuKxV3YJenONO9XWcJpHGc8BBalU5JXn/0e3+PfO4/cVoMcrCMVu6x/jWFnNqiOSEUQsm53mMqDzXHRM7ZZGOomPx9emV7uskrBg0TKYr8m5sZxkc5r5qGl+hmiOKsv3eC3KNJopw41ZGDvyMirfmUspFROTYGMlih1g0cEFFt/081RGJ0NejLUj7+HidUoJGYccEqGG5ggtcx3LEDu5uXKYezLQd47BJ7IPVv1Qi2+9Vbi/Pvh9qjFEHXfV3bVjWmroMLxMbiLMt/n0= sven@svenbuntu
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDWdRfXO5G0QXN0BpeHLXCYoJVfpwbs+ResxWlgpkGht9cE6PkcXO5QNJTkrsXa4bQYnCVa4SySGuVHoGSoEF/VXR48Qab7aOR3rNCZ07jkZBVAXNulYh8On23TOcLeizksDQ+oYySM1Y6Xrci2jAXS8U75D069BaH1UgOlAEk90KyWiE7yqn+LYeAR2jRXEh2cgy+jpm2iFX90G/UaSGCgfHAsJPac5eDKQ5nRnZaouiYB20Rw+PuSOMYV7eq1Mi9ElAQulg4dxLqJxx6zDO1zfchzPSsAGhR1espcJpfzxMNfBk30LgsrEVoq8HGxoumu2OvMEMxiPvZhhzQQgb248ZcYS48PKLGLdS5+XsedZXBZzdOf7pszdXD9YCXbfZOdW3lxLp0Q2s9/sglntyvA8gPZEtfRfLjC4N7R/XO63RfEQc3qVDvr/L7xVj6IByd7II5fXicL8tqjB99onOZEFgR9nLPWnKNbQ30E/O6QoPcLpWxnJwzKuddJQxwpxvs= sven@svenbuntu
