---

- name: generic
  hosts: all
  roles:
    - { name: hosts, tags: hosts }
    - { name: cephhome, tags: cephhome }
- name: execute nodes
  hosts: slurm-node
  roles:
    - { name: nvidia-drivers, tags: nvidia-drivers }
    - { name: singularity, tags: singularity }

- name: "deepops: setup slurm"
  hosts: all
  vars:
    deepops_dir: /opt/deepops
    user: [] # ???? https://github.com/NVIDIA/deepops/blame/1bc7988cb5d0aa64ae81dd3492536994f42f13ba/roles/slurm/tasks/controller.yml#L138

  tasks:
    - name: figure out cpu, gpu and memory
      include_role:
        name: facts
        tasks_from: main

    - name: build and install slurm on all nodes
      include_role:
        name: slurm
        tasks_from: main

- name: controller nodes
  hosts: slurm-master
  roles:
    - { name: slurmdbd, tags: slurmdbd }

