---

- name: generic
  hosts: all
  roles:
    - { name: hosts, tags: hosts }
    - { name: cephhome, tags: cephhome }
- name: execute nodes
  hosts: slurm-node
  roles:
    - { name: nvidia-drivers, tags: nvidia-drivers }
    - { name: singularity, tags: singularity }

- name: "deepops: setup slurm"
  hosts: all
  vars:
    deepops_dir: /opt/deepops
    user: [] # ???? https://github.com/NVIDIA/deepops/blame/1bc7988cb5d0aa64ae81dd3492536994f42f13ba/roles/slurm/tasks/controller.yml#L138
    slurm_conf_template: "templates/slurm.conf.j2"
    slurm_version: "21.08.8-2"
    slurm_src_url: "https://download.schedmd.com/slurm/slurm-{{ slurm_version }}.tar.bz2"

  tasks:
    - name: figure out cpu, gpu and memory
      include_role:
        name: facts
        tasks_from: main

    - name: ensure slurm.conf.d directory
      file:
        state: directory
        path: /etc/slurm/slurm.conf.d

    - name: add pr environment config
      template:
        src: slurm.conf.d/{{ inventory_file | basename }}.conf
        dest: /etc/slurm/slurm.conf.d/{{ inventory_file | basename }}.conf

    - name: build and install slurm on all nodes
      include_role:
        name: slurm
        tasks_from: main

  # the pam_slurm_adopt module is unable to find
  # libslurm.so if this is not updated - its not a big deal
  # but should properly be fixed upstream
- name: "small deepops fixes"
  hosts: all
  tasks:
    - name: run ldconfig to update cache
      command: ldconfig

- name: controller nodes
  hosts: slurm-master
  roles:
    - { name: slurmdbd, tags: slurmdbd }
