---

- name: common configuration for all hosts
  hosts: all
  vars:
    deepops_dir: /opt/deepops

  tasks:
    - name: build slurm on all nodes
      include_role:
        name: slurm
        tasks_from: main

  roles:
    - { name: hosts, tags: hosts }

- name: execute nodes
  hosts: exec


- name: controller nodes
  hosts: controller
